version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nats-streaming-server:
    image: nats-streaming
    ports:
      - "4222:4222"  # Порт NATS Streaming Server
      - "8222:8222"  # HTTP порт NATS Streaming Server
volumes:
  habrdb-data: